-- creating the database
----- creating database and learning sql from the scracth ;

CREATE DATABASE university ;
USE university ;
CREATE TABLE branch (
		ID INT PRIMARY KEY ,
		SUDENTNAME VARCHAR (100),
        AGE INT NOT NULL 
 );       
DROP TABLE branch ;
DROP DATABASE university ;
SELECT * FROM branch ;

-------# IF EXISTS AND IF NOT EXISTS QUERIES -----//

CREATE DATABASE IF NOT EXISTS college ;
DROP DATABASE IF EXISTS college ;

------------ # TABLES RELATED QUERIES ---------\\\/////
# 1. TO SELECT AND VIEW ALL COLUMN :
SELECT * FROM branch ;

# 2 . TO INSERT VALUE IN THE COLUMNS ;
INSERT INTO branch
(ID,SUDENTNAME,AGE)
VALUES
(101,"lucky",21),
(103,"bholu",29),
(102,"ankit",30),
(104,"romibabu",34),
(110,"raunak",22);
# to VIEW UPPER VALUE WRITE :
SELECT * FROM branch;
SELECT ID,AGE FROM branchs;
SELECT (ID),(AGE) FROM branchs;

ALTER TABLE branch
CHANGE COLUMN SUDENTNAME STUDENTNAME VARCHAR(50) ;

ALTER TABLE branch
ADD COLUMN cgpa  INT NOT NULL ;

ALTER TABLE branch
DROP COLUMN cgpa ;

ALTER TABLE branch
RENAME TO BRANCHS ;

SELECT * FROM BRANCHS ;

## VARIOUS METHODS AND ATTRIBUTES ON FOLLOWING TABLES;

SELECT * FROM branch WHERE (AGE >=27) AND (ID >100) ;
SELECT * FROM branch WHERE (AGE >=30) OR (ID <102) ;

# ANOTHER METHODS ;
INSERT INTO branchs
VALUES(119,"sovietbabu",54);
SELECT * FROM branchs ;

### ------ PRACTISE QUESTION 1. CREATE A DATABASE FOR YOUR COMPANY NAME XYZ .
CREATE DATABASE xyz_company ;
USE xyz_company;
CREATE TABLE employee(
	   ID INT PRIMARY KEY,
       NAME VARCHAR (60),
       SALARY INT 
);
INSERT INTO employee 
(ID,NAME,SALARY)
VALUES
(1, "RAM",230000),
(2,"lucky",430000),
(3,"casey",40000),
(4,"adam",25000),
(5,"bob",30000);

SELECT * FROM employee;

# VARIOUS METHODS AND ATTRIBUTES  ON FOLLOWING DATABASE AND TABLEs :

SELECT ID,SALARY FROM employee WHERE (ID >2) AND (ID <4) ;
SELECT ID,SALARY FROM employee WHERE (ID >=2) OR (SALARY >=40000) ;
SELECT ID,SALARY FROM employee WHERE ID BETWEEN 1 AND 6
AND SALARY BETWEEN 35000 AND 670000 ;

SELECT * FROM employee WHERE SALARY IN (25000, 230000)
OR ID IN (2,6);

SELECT * FROM employee WHERE SALARY NOT IN (25000,450000);

# 					 ----- LIKE OPERATOR -------- 
SELECT * FROM dim_customer ;
SELECT
    * 
FROM 
   dim_customer
WHERE
    first_name LIKE 'T%Y' ;   
    
SELECT
    * 
FROM 
   dim_customer
WHERE
    first_name LIKE 'T_M%Y'
    OR last_name LIKE 'L%S';

# 					------- ALIAS OPERATER ------////

SELECT *,
     first_name AS EARLIER_NAME,
     last_name AS PREVIOUS_NAME
FROM
    dim_customer ;     


### ------- LIMIT CLAUSES \ GIVES VALUE UPT0 THE GIVEN NUMBER OR GIVEN RANGE :
SELECT
     (ID), (NAME)
FROM employee
LIMIT 3 ;     

### ORDER BY CLAUSES \\\////----- TO ARRANGE IN ASECENDING AND DESCENDING 
SELECT * FROM employee
ORDER BY ID DESC;

SELECT * FROM employee
ORDER BY SALARY ASC;

### AGEEREGATE FUNCTIONS ;
SELECT MAX(SALARY) FROM employee;
SELECT MIN(SALARY) FROM employee ;
SELECT SUM(SALARY) FROM employee ;
SELECT AVG(SALARY) FROM employee ;
SELECT COUNT(SALARY) FROM employee ;

SELECT * FROM employee ;

##  ------- GROUP BY CLAUSE 0----- COUNT NUMBER OF STUDENT IN EACH ID ?
SELECT NAME 
FROM employee
GROUP BY NAME ;

SELECT ID ,COUNT(NAME)
FROM employee
GROUP BY ID;

## PRACTISE QUESTION Q3 ?\\\ WRITE THE QUERY TO FIND AVG SALARY IN EACH NAME IN ASCENDING ORDER
SELECT ID ,AVG(SALARY)
FROM employee
GROUP BY ID
ORDER BY ID ASC;

SELECT ID ,AVG(SALARY)
FROM employee
GROUP BY ID
ORDER BY ID DESC;

### ----- PRACTISE Q4 ? FOR THE GIVEN TABLE FIND THE TOTAL PAYMENT ACCORDING TO EACH PAYMENT METHODS ?
CREATE TABLE PAYMENT (
	   CUST_ID INT PRIMARY KEY,
       CUSTOMER VARCHAR(100),
       MODE VARCHAR(70),
       CITY VARCHAR(30)
 );      
 INSERT INTO PAYMENT
 (CUST_ID,CUSTOMER,MODE,CITY)
 VALUES
 (101,"OLIVIABARRET","NETBANKING","PORTLAND"),
 (102,"ETHAN SINCLAIR","CREDITCARD","MIAMI"),
 (103,"MAYA HERNADEZ","CREDITCARD","SEATTLE"),
 (104,"LIAN DONOVAN","NETBANKING","DENVER"),
 (105,"SOPHIA NGUYEN","CREDITCARD","NEWORELANS"),
 (106,"CALEB FOSTER","DEBITCARD","MINNEAPOLIS"),
 (107,"AVA PATEL","DEBITCARD","PHOENIX");
 
 SELECT * FROM PAYMENT ;
 
 SELECT MODE , COUNT(CUSTOMER)
 FROM PAYMENT
 GROUP BY MODE
 ORDER BY MODE DESC ;
 
 #### ------- //<><< HAVING CLAUSES ....... ALWAYS WRITTEN AFTER GROPUING CLAUSES? 
 
# Q1. COUNT NO OF STUDENTS IN EACH ID WHERE MAX SALARY CROSS 90 ..

SELECT ID ,COUNT(NAME)
FROM employee
GROUP BY ID 
HAVING MAX(SALARY) > 35000 ;

### -------><>< TABLE RELATED QUERIES .....
# 1. UPDATE (TO UPDATE EXISTING ROWS)....
UPDATE employee
SET NAME = "LUCKY"
WHERE NAME = "RAM" ;

UPDATE employee
SET SALARY = 650000
WHERE SALARY <= 30000 ;

SET SQL_SAFE_UPDATES = 0 ;

SELECT * FROM PAYMENT ;
 
 ### -----><><<////   	ALTER ( TO CHANGE THE SCGHEMA )``
 # 1. ADD COLUMN ;
 ALTER TABLE PAYMENT
 ADD COLUMN MARKS INT NOT NULL ;
 
 # TO FILLL UPPER COLUMN USING UPDATE METHODS	
 UPDATE PAYMENT
 SET MARKS = 8324
 WHERE CUST_ID =101;
 UPDATE PAYMENT
 SET MARKS = 8748
 WHERE CUST_ID = 102;
 UPDATE PAYMENT
 SET MARKS = 3546
 WHERE CUST_ID = 103;
 UPDATE PAYMENT
 SET MARKS = 2434
 WHERE CUST_ID = 104;
 UPDATE PAYMENT
 SET MARKS = 1524
 WHERE CUST_ID = 105;
 UPDATE PAYMENT
 SET MARKS = 9823
 WHERE CUST_ID = 106;
 UPDATE PAYMENT
 SET MARKS = 9349
 WHERE CUST_ID = 107;
 
# 2 . DROP COLUMN 
ALTER TABLE PAYMENT
DROP COLUMN MARKS ;

SELECT * FROM PAYMENT_METHODS ;

 # 3 . RENAME TABLE
 ALTER  TABLE PAYMENT
 RENAME TO PAYMENT_METHODS;
 
 # 4 . CHANGE COLUMNS (RENAME)
 ALTER TABLE PAYMENT_METHODS
 CHANGE COLUMN CUST_ID CUSTOMER_ID INT ;
 
 
SELECT * FROM PAYMENT_METHODS;
SHOW DATABASES ;
SHOW TABLES ;
 
CREATE TABLE STUDENT(
        ROLL_NO INT PRIMARY KEY,
        NAME VARCHAR (200),
        MARKS INT NOT NULL,
        GRADE VARCHAR(10),
        CITY VARCHAR(30)
 );       
 
 INSERT INTO STUDENT 
 (ROLL_NO,NAME,MARKS,GRADE,CITY)
 VALUE
 (101,"ANIL",78,"C","PUNE"),
 (102,"BHUMIKA",93,"A","MUMBAI"),
 (103,"CHETAN",85,"B","MUMBAI"),
 (104,"DHRUV",96,"A","DELHI"),
 (105,"EMANUEL",12,"F","DELHI"),
 (106,"FARAH",82,"B","DELHI") ;
 
SELECT * FROM STUDENT ;
 
 #### -----><<><>< PRACTISE QUESTION 1. IN THE STUDENT TABLE (a). CHANGE TYE NAME OF COLUMN TO FULL_NAME , 
 #(B). DELETE ALL STUDENT WHO SCORED MARK LESS THAN 80.,(C). DELETE THE COLUMN FOR GRADES.---- 

# 1 . ANS .
ALTER TABLE STUDENT
CHANGE COLUMN NAME FULL_NAME VARCHAR(60) ;

# 2 . ANS .. 
DELETE FROM STUDENT
WHERE MARKS < 80 ;

# 3 . ANS ... 
ALTER TABLE STUDENT
DROP COLUMN GRADE ;

# 4 . FROM OWN SELF     ADD COLUMN NAME CGPA 
ALTER TABLE STUDENT
ADD COLUMN CGPA INT NOT NULL ;

# 5 . ANS RENAME THE TABLE TO NEW STUDENT DATA 
ALTER TABLE STUDENT
RENAME TO STUDENT_NEWDATA ;

# 6 . ANS    MODIFY COLUMN MARKS TO INT
ALTER TABLE STUDENT
MODIFY MARKS INT ;
 
SELECT * FROM STUDENT_NEWDATA ;
 
 # #   TO ADD VALUE IN THE CGPA COLUMN 
 UPDATE STUDENT_NEWDATA
 SET CGPA = 6.9
 WHERE ROLL_NO = 102 ;
 
 UPDATE STUDENT_NEWDATA
 SET CGPA = 5.5
 WHERE ROLL_NO = 103 ;
 
 UPDATE STUDENT_NEWDATA
 SET CGPA = 4.9
 WHERE ROLL_NO = 104 ;
 
 UPDATE STUDENT_NEWDATA
 SET CGPA = 6.9
 WHERE ROLL_NO = 106 ;
 
 ### 7. TRUNCATE (TO DELETE THE DATA OF THE TABLE )
 
 TRUNCATE TABLE STUDENT_NEWDATA;
 DROP TABLE STUDENT_NEWDATA ;
 SELECT * FROM STUDENT ;
 
 #####  						---------><> JOINS ><><><<-----------><><><
CREATE TABLE ASPIRANTS(
	   STUDENT_ID INT NOT NULL,
       NAME VARCHAR (70)
);  
CREATE TABLE COURSE(
       STUDENT_ID INT NOT NULL,
       COURSE VARCHAR(70)
);       
SELECT * FROM aspirants ;
INSERT INTO ASPIRANTS
(ID,NAME)
VALUE 
(101,"ADAM"),
(102,"BOB"),
(103,"CASEY");
 
 INSERT INTO COURSE 
 (ID,COURSE)
 VALUE 
 (102,"ENGLISH"),
 (105,"MATH"),
 (103,"SCIENCE"),
 (107,"COMPUTER SCIENCE");
 
ALTER TABLE ASPIRANTS
CHANGE COLUMN STUDENT_ID ID INT NOT NULL ;

ALTER TABLE COURSE
CHANGE COLUMN STUDENT_ID ID INT NOT NULL ;
 
 SELECT * FROM ASPIRANTS ;
 SELECT * FROM COURSE ;
 
 ###  				1. INNNER JOINS ------- return record THAT HAVE MATCHING VALUE  IN BOTH THE TABLES .....
 SELECT * 
 FROM ASPIRANTS
 INNER JOIN COURSE
 ON ASPIRANTS.ID = COURSE.ID ;
 
 ### 				2 . LEFT JOINS -------- RETURN ALL RECORDS FROM LEFT TABLE AND MATCHING RECORD FROM THE RIGHT TABLE ;
 
SELECT  *
FROM ASPIRANTS AS A
LEFT JOIN COURSE AS C
ON A.ID = C.ID ;

#### 				3 . RIGHT JOINS ------- RETURN ALL RECORDS FROM RIGHT TABLE AND MATCHING RECORD FROM THE LEFT TABLE ;
 
 SELECT *
 FROM ASPIRANTS AS A
 RIGHT JOIN COURSE AS C
 ON A.ID = C.ID ;
 
## 					 4. FULL JOINS ---------- RETURN ALL RECORDS WHEN THERE IS MATCH IN EITHER LEFT OR RIGHT TABLE ...alter

SELECT * 
FROM ASPIRANTS AS A
LEFT JOIN COURSE AS C
ON A.ID = C.ID
UNION
SELECT * 
FROM ASPIRANTS AS A
RIGHT JOIN COURSE AS C
ON A.ID = C.ID ;

## ---			5 . SELF JOINS ---------- REGULAR JOIN BETWEEN TWO TABLES

SELECT * 
FROM ASPIRANTS AS A
JOIN COURSE AS C 
ON A.ID = C.ID ;

# 					6 . UNION --------- COMBINE BOTH THE THE TABLES -----

SELECT 
     * 
FROM
    COURSE
UNION 
SELECT
     *
FROM
    ASPIRANTS ;     


SHOW DATABASES ;
SHOW TABLES ;
SELECT * FROM actor ; 
SELECT * FROM  STUDENT ;

#### --------- ALIAS ---------( TO CHANGE THE NAME OF THE COLUMN AS TEMPRORARY FOR VIEWING AS RESULT) ....

SELECT ROLL_NO AS R ,
	   NAME AS N,
       MARKS AS M,
       CITY AS C 
 FROM STUDENT ;      
       
### 					------ EXECUTIONS FLOW CHART

SELECT CITY , SUM(MARKS) AS TOTAL_MARKS
FROM STUDENT 
WHERE MARKS > 40
GROUP BY CITY 
HAVING SUM(MARKS) > 40
ORDER BY CITY 
LIMIT 6 ;

# 			2 . USING IT ON QUESTIONS
SELECT 
     category , AVG(unit_price) AS AVG_PRICE
FROM 
    dim_products
WHERE 
   brand = 'BRANDE'   
GROUP BY 
       category
HAVING
    AVG_PRICE > 500
ORDER BY 
    category ASC ;       


SELECT * FROM dim_date ;
ALTER TABLE dim_date
RENAME TO DIM_DATE ;
SELECT * FROM dim_customer ;
ALTER TABLE dim_customer
RENAME TO DIM_CUSTOMER; ;
SELECT * FROM dim_product;
ALTER TABLE dim_product
RENAME TO DIM_PRODUCTS ;
SELECT * FROM dim_store ;
ALTER TABLE dim_store
RENAME TO DIM_STORES ;
SELECT * FROM fact_sales ;
ALTER TABLE fact_sales
RENAME TO FACT_SALES;
 
 CREATE TABLE DUPLICATED (
         NAME VARCHAR (30),
         ID INT PRIMARY KEY,
         EMAIL CHAR(49),
         MARKS INT NOT NULL
) ; 
 
 INSERT INTO DUPLICATED
 VALUES
 ("LUCKY",101,"AA",56),
 ("BHOLU",102,"BB",78),
 ("LUCKY",103,"BB",78),
 ("BHOLU",104,"AA",67),
 ("GOLU",105,"BB",67) ;
 SELECT * FROM CUSTOMERS ;
 ALTER TABLE CUSTOMERS
 ADD COLUMN CITY VARCHAR(90) ;
 
UPDATE CUSTOMERS
SET CITY = "GAYA"
WHERE ID = 101 ;

UPDATE CUSTOMERS
SET CITY = "GAYA"
WHERE ID = 102 ;
UPDATE CUSTOMERS
SET CITY = "PATNA"
WHERE ID = 103 ;
UPDATE CUSTOMERS
SET CITY = "IMAMGANJ"
WHERE ID = 104 ;
UPDATE CUSTOMERS
SET CITY = "PATNA"
WHERE ID = 105 ;

ALTER TABLE CUSTOMERS
DROP COLUMN CITY ;

## 					------- TRANSFORMATIONS -------- ///
##     1 . NUMERIC TRANSFORMATIONS 

SELECT 
	  unit_price * 0.90 AS DISCOUNTED_PRICE,
      unit_price + 10 AS TAXED_PRICE,
      unit_price / 10 AS FRACTIONAL_PRICE,
      ROUND(unit_price,2) AS ROUNDED_PRICE 
FROM
   DIM_PRODUCTS; 
   
##  		2 . DATE TRANSFORMATIONS ------ ///  TO GET CURRENT TIMESTAMP
SELECT * FROM DIM_DATE ;
SELECT
    date,
    NOW() AS 'CURRENT_TIMESTAMP',        # TO GET ALL TIMESTAMP SAME AS UTC_TIMESTAMP()
    utc_date(),    # TO GET CURRENT DATE
    utc_time(),      # TO GET CURRENT TIME
    utc_timestamp()   # TO GET ALL DATE AND TIME AND YAER 
FROM 
   DIM_DATE ;    

#    2 . ---- TO GET NAME OF MONTH, DAY, WEEKDAY, YEAR ,ETC.
SELECT 
    date ,
    YEAR(date),
    MONTH(date),
    DAY(date),
    DATE(date),
    WEEKDAY(date),
    DAYNAME(date),
    MONTHNAME(date)
FROM 
   dim_date ;
    
   ## ----- 3 .  TO ADD OR SUBSTRACT (CHAGNGE) TIMESTAMP MEANS DAY,MONTH ,YEAR,HOUR,MIN ----
   
SELECT
     date,
     DATE(utc_timestamp()),
     adddate(date,2),
     SUBDATE(date,2),
     DATEDIFF(utc_timestamp(),date) AS TOTAL_DAY
FROM
     DIM_DATE ;
    
## 				-------- 4 . TYPE CASTINGS ---( TO CHANGE THE DTYPE OF ANY COLUMN LIKE MODIFY FUNCTIONS IN EASY WAY)

SELECT   
     customer_key ,
     CAST(customer_key AS CHAR(20))
FROM 
   DIM_CUSTOMER ;
   
### 					----- STRINGS FUNCTIONS ------- /////\\ 

## 				1  . concatenanate--------- --
SELECT * ,
    CONCAT(first_name,' ',last_name) AS FULL_NAMES
FROM
   DIM_CUSTOMER ;
   
## 				 2. LENGTH -----\\///
SELECT 
    *,
    LENGTH(country)AS COUNTRY_SIZE ,
	LENGTH(CITY) AS CITY_SIZE
FROM 
   DIM_CUSTOMER ;    
   
## 				 3 . UPPER / LOWER -------
SELECT *,
     UPPER(city) AS FULL_CITY,
     LOWER(country) AS LOWER_COUNTRYNAME
FROM
   DIM_CUSTOMER ;
   
### 				 4 . SUBSTRINGS =-------- 
SELECT *,
     SUBSTRING(email,1,5),
     SUBSTRING(city,1,3),
     SUBSTRING(country,1,7)
FROM
   DIM_CUSTOMER ;
   
## 					5 . REPLACE -------\\\///
SELECT * ,
    REPLACE(email,'@','#') AS NEW_EMAILS
FROM 
    DIM_CUSTOMER ;
  
## 						 6 . LEFT / RIGHT FUNCTI0NS
SELECT * ,
      LEFT(country,3),
      RIGHT(email,7)
FROM
  DIM_CUSTOMER ;
  
## 						 7 . REVERSE / REPEAT------ 
SELECT * ,
     REVERSE(email),
     REPEAT(first_name ,3)
FROM 
   DIM_CUSTOMER ;

#### 						 --- CONDITIONALS -------\\\/// 

SELECT *,
      CASE
      WHEN unit_price <= 100 THEN 'AFFORDABLE'
      WHEN unit_price <= 200 THEN 'NORMAL'
      ELSE 'EXPENSIVE(BUT not for you )'
      END AS PRICE_CATEGORY
FROM
   DIM_PRODUCTS ;

### 			 2 . CASE
SELECT * ,
       CASE
       WHEN unit_price <= 200 AND category ='clothing' THEN 'AFFORDABLE'
       WHEN unit_price <= 300 AND category ='clothing' THEN 'NORMAL'
       WHEN unit_price > 200 AND category = 'clothing' THEN 'EXPENSIVE'
       ELSE CONCAT('NOT FOR YOU',category)
       END AS PRICE_CATEGORY
FROM 
   DIM_PRODUCTS;
   
##3 					------- WINDOW FUNCTIONS ------///\\\\
SELECT * FROM dim_products ;

SELECT *,
      SUM(unit_price) OVER (ORDER BY launch_date) AS TOTALS_UNITPRICE
FROM 
   DIM_PRODUCTS ;

## 					 ---- RANKINGS # -----\\/////
SELECT * FROM DIM_PRODUCTS ;
SELECT 
    unit_price,
    ROW_NUMBER() OVER(ORDER BY unit_price) AS 'ROW_NUMBER',
    RANK() OVER(ORDER BY unit_price) AS 'RANK',
    DENSE_RANK() OVER(ORDER BY unit_price) AS 'DENSE_RANK'
FROM
    DIM_PRODUCTS;

### 				 2 . PARTITION ------\\\/// 

SELECT
      * ,
      ROW_NUMBER() OVER (PARTITION BY category ORDER BY unit_price) AS 'ROW_NUMBER',
      RANK() OVER (PARTITION BY category ORDER BY unit_price) AS 'RANK',
      DENSE_RANK() OVER (PARTITION BY category ORDER BY unit_price) AS 'ROW_NUMBER'
FROM 
   DIM_PRODUCTS ;
   
   
### 				 ----- SUBQUERY ----- \\\\\//// 

SELECT AVG(unit_price) AS AVERAGE
FROM DIM_PRODUCTS ;
### 			--- NOW WRITTING SUBQUERY

SELECT 
    * 
FROM 
    DIM_PRODUCTS
WHERE
    unit_price > (SELECT AVG(unit_price) FROM DIM_PRODUCTS); 

### 						------ 2. QUERY IN QUERY IN QUERY 

SELECT
	SUBQUERY_TABLE. * 
FROM 
(
  SELECT
       * 
  FROM 
     DIM_PRODUCTS
  WHERE 
  unit_price > (SELECT AVG(unit_price) FROM DIM_PRODUCTS)
)  SUBQUERY_TABLE
WHERE 
   product_name = "Figure Method" OR product_name = "Pressure That";
SELECT * FROM dim_products ;


### 					------- REAL TIME SCENARIOS ---------\\\\><><><///// 
## 			 1. SCENARIO 1 . (FINDING NTH values) ---   QUESTION LIKE --- FIND THE  5TH MOST HIGHEST UNIT_PRICE FROM THE DATA

SELECT 
     *,
     DENSE_RANK() OVER(ORDER BY unit_price ASC) AS RANKING
FROM
    DIM_PRODUCTS ;
    
## ------ NOW MAKE IT IN SUBQUERY TO GET SPECIFIC ONE VALUE ) LIKE I HAVE TO GET 5TH MOST UNIT_PRICE

SELECT 
     SUBQUERY. * 
FROM 
(
  SELECT 
       * ,
       DENSE_RANK() OVER(ORDER BY unit_price ASC) AS RANKING
  FROM 
     DIM_PRODUCTS 
) SUBQUERY
WHERE 
    RANKING = 5 ;

## 						 --- TO GET THE UNIT_PRICE OF  99TH TERMS --- LETS DO IT ---

SELECT * ,
       DENSE_RANK() OVER(ORDER BY unit_price ASC) AS RANKED
FROM 
   DIM_PRODUCTS ;
   
## 						 NOW GOING THROUGH SUBQUERY

SELECT 
     SUBQUERY. *
FROM
(
   SELECT * ,
       DENSE_RANK() OVER( PARTITION BY category ORDER BY unit_price ASC) AS RANKED
   FROM 
   DIM_PRODUCTS 
) SUBQUERY
WHERE RANKED = 7 ;

#### 						 2 . SCENARIO 2 ..( REMOVING DUPLICATES) --------\\\/// >>><<><><><  BY ROW_NUMBER

SELECT * FROM CUSTOMERS_NEW ;
SELECT 
     *, 
     ROW_NUMBER() OVER(PARTITION BY NAME ORDER BY ID ASC) AS DEDUP
FROM
   CUSTOMERS ;
   
## 	------		---- NOW TO DELETE  
SELECT * FROM CUSTOMERS ;
SELECT
    SUBQUERY. *
FROM
(
   SELECT 
     *, 
     ROW_NUMBER() OVER(PARTITION BY NAME ORDER BY ID ASC) AS DEDUP
   FROM
   CUSTOMERS 
) SUBQUERY
WHERE DEDUP = 1 ;

### 					 --- DELETING IT TAKING PARTITION AS EMAIL 0---------- 
SELECT
    SUBQUERY. *
FROM
(
   SELECT 
     *, 
     ROW_NUMBER() OVER(PARTITION BY EMAIL ORDER BY ID ASC) AS DEDUP
   FROM
   CUSTOMERS 
) SUBQUERY
WHERE DEDUP = 1 ;
SELECT * FROM DIM_PRODUCTS ;
## #                			FINDING THE 10 TH HIGHETS VALUE -----------><><><><>< ----
SELECT 
     SUBQUERY.*
FROM
(
SELECT
	  *,
	  DENSE_RANK() OVER(ORDER BY unit_price ASC) AS RANKED
FROM 
    DIM_PRODUCTS
) SUBQUERY
WHERE 
    RANKED = 10 ;
    
### 							----- FINDING THE DUPLICATED VALUE BY USING ROW NUMBERS ------><><><> 
SELECT 
     SUBQUERY.*
FROM 
(
SELECT 
     *,
     ROW_NUMBER() OVER(PARTITION BY category ORDER BY unit_price) AS dedup
FROM 
    DIM_PRODUCTS 
) SUBQUERY
WHERE 
  dedub = 1 ;
SELECT * FROM CUSTOMERS ;
    


 

 
 
 
 